import type { ModeloCelular } from "./types";

/**
 * Catálogo de modelos (RockB2B print-h5 / deviceSn RMEACGBQYXL87Z).
 * Dimensões derivadas da proporção width×length do molde de impressão.
 * IDs estáveis: iphone-15, samsung-s24, iphone-17-pro-max (produtos existentes).
 */
export const MODELOS: ModeloCelular[] = [
  {
    id: "redmi-note-10-pro-max",
    marca: "Xiaomi",
    modelo: "Redmi Note 10 Pro Max",
    larguraPx: 1870,
    alturaPx: 3200,
  },
  {
    id: "mi-12-pro",
    marca: "Xiaomi",
    modelo: "12 Pro",
    larguraPx: 1733,
    alturaPx: 3200,
  },
  {
    id: "mi-12x",
    marca: "Xiaomi",
    modelo: "12X",
    larguraPx: 1778,
    alturaPx: 3200,
  },
  {
    id: "mi-12",
    marca: "Xiaomi",
    modelo: "12",
    larguraPx: 1778,
    alturaPx: 3200,
  },
  {
    id: "mi-11t",
    marca: "Xiaomi",
    modelo: "11T",
    larguraPx: 1778,
    alturaPx: 3200,
  },
  {
    id: "mi-11t-pro",
    marca: "Xiaomi",
    modelo: "11T Pro",
    larguraPx: 1778,
    alturaPx: 3200,
  },
  {
    id: "redmi-note-10-pro-china",
    marca: "Xiaomi",
    modelo: "Redmi Note 10 Pro (China)",
    larguraPx: 1870,
    alturaPx: 3200,
  },
  {
    id: "redmi-note-10s",
    marca: "Xiaomi",
    modelo: "Redmi Note 10S",
    larguraPx: 1870,
    alturaPx: 3200,
  },
  {
    id: "mi-11-lite-4g",
    marca: "Xiaomi",
    modelo: "11 Lite 4G",
    larguraPx: 1795,
    alturaPx: 3200,
  },
  {
    id: "mi-11-lite-5g",
    marca: "Xiaomi",
    modelo: "11 Lite 5G",
    larguraPx: 1795,
    alturaPx: 3200,
  },
  {
    id: "galaxy-s26-ultra",
    marca: "Samsung",
    modelo: "Galaxy S26 Ultra",
    larguraPx: 1837,
    alturaPx: 3200,
  },
  {
    id: "galaxy-s26-plus",
    marca: "Samsung",
    modelo: "Galaxy S26+",
    larguraPx: 1792,
    alturaPx: 3200,
  },
  {
    id: "galaxy-s26",
    marca: "Samsung",
    modelo: "Galaxy S26",
    larguraPx: 1839,
    alturaPx: 3200,
  },
  {
    id: "galaxy-s25-edge",
    marca: "Samsung",
    modelo: "Galaxy S25 Edge",
    larguraPx: 1824,
    alturaPx: 3200,
  },
  {
    id: "galaxy-s25-ultra",
    marca: "Samsung",
    modelo: "Galaxy S25 Ultra",
    larguraPx: 1831,
    alturaPx: 3200,
  },
  {
    id: "galaxy-s25-plus",
    marca: "Samsung",
    modelo: "Galaxy S25+",
    larguraPx: 1812,
    alturaPx: 3200,
  },
  {
    id: "galaxy-s25",
    marca: "Samsung",
    modelo: "Galaxy S25",
    larguraPx: 1810,
    alturaPx: 3200,
  },
  {
    id: "galaxy-s24-fe",
    marca: "Samsung",
    modelo: "Galaxy S24 FE",
    larguraPx: 1857,
    alturaPx: 3200,
  },
  {
    id: "galaxy-s24-ultra",
    marca: "Samsung",
    modelo: "Galaxy S24 Ultra",
    larguraPx: 1770,
    alturaPx: 3200,
  },
  {
    id: "galaxy-s24-plus",
    marca: "Samsung",
    modelo: "Galaxy S24+",
    larguraPx: 1812,
    alturaPx: 3200,
  },
  {
    id: "samsung-s24",
    marca: "Samsung",
    modelo: "Galaxy S24",
    larguraPx: 1810,
    alturaPx: 3200,
  },
  {
    id: "galaxy-s23-fe",
    marca: "Samsung",
    modelo: "Galaxy S23 FE",
    larguraPx: 1847,
    alturaPx: 3200,
  },
  {
    id: "galaxy-a34",
    marca: "Samsung",
    modelo: "Galaxy A34",
    larguraPx: 1770,
    alturaPx: 3200,
  },
  {
    id: "galaxy-a14-5g",
    marca: "Samsung",
    modelo: "Galaxy A14 5G",
    larguraPx: 1796,
    alturaPx: 3200,
  },
  {
    id: "galaxy-s23-5g",
    marca: "Samsung",
    modelo: "Galaxy S23 5G",
    larguraPx: 1810,
    alturaPx: 3200,
  },
  {
    id: "galaxy-s23-plus",
    marca: "Samsung",
    modelo: "Galaxy S23 Plus",
    larguraPx: 1812,
    alturaPx: 3200,
  },
  {
    id: "galaxy-s23-ultra",
    marca: "Samsung",
    modelo: "Galaxy S23 Ultra",
    larguraPx: 1770,
    alturaPx: 3200,
  },
  {
    id: "galaxy-a33-5g",
    marca: "Samsung",
    modelo: "Galaxy A33 5G",
    larguraPx: 1778,
    alturaPx: 3200,
  },
  {
    id: "galaxy-a13",
    marca: "Samsung",
    modelo: "Galaxy A13",
    larguraPx: 1859,
    alturaPx: 3200,
  },
  {
    id: "galaxy-a73",
    marca: "Samsung",
    modelo: "Galaxy A73",
    larguraPx: 1853,
    alturaPx: 3200,
  },
  {
    id: "galaxy-a53-5g",
    marca: "Samsung",
    modelo: "Galaxy A53 5G",
    larguraPx: 1849,
    alturaPx: 3200,
  },
  {
    id: "galaxy-s22-plus-5g",
    marca: "Samsung",
    modelo: "Galaxy S22 Plus 5G",
    larguraPx: 1921,
    alturaPx: 3200,
  },
  {
    id: "galaxy-s22-ultra-5g",
    marca: "Samsung",
    modelo: "Galaxy S22 Ultra 5G",
    larguraPx: 1873,
    alturaPx: 3200,
  },
  {
    id: "galaxy-s22-5g",
    marca: "Samsung",
    modelo: "Galaxy S22 5G",
    larguraPx: 1861,
    alturaPx: 3200,
  },
  {
    id: "galaxy-s21-fe-5g",
    marca: "Samsung",
    modelo: "Galaxy S21 FE 5G",
    larguraPx: 1814,
    alturaPx: 3200,
  },
  {
    id: "galaxy-s20-ultra-5g",
    marca: "Samsung",
    modelo: "Galaxy S20 Ultra 5G",
    larguraPx: 1824,
    alturaPx: 3200,
  },
  {
    id: "galaxy-a22-5g",
    marca: "Samsung",
    modelo: "Galaxy A22 5G",
    larguraPx: 1853,
    alturaPx: 3200,
  },
  {
    id: "galaxy-a52",
    marca: "Samsung",
    modelo: "Galaxy A52",
    larguraPx: 1798,
    alturaPx: 3200,
  },
  {
    id: "galaxy-a52-5g",
    marca: "Samsung",
    modelo: "Galaxy A52 5G",
    larguraPx: 1798,
    alturaPx: 3200,
  },
  {
    id: "galaxy-a72",
    marca: "Samsung",
    modelo: "Galaxy A72",
    larguraPx: 1770,
    alturaPx: 3200,
  },
  {
    id: "galaxy-a32-5g",
    marca: "Samsung",
    modelo: "Galaxy A32 5G",
    larguraPx: 1814,
    alturaPx: 3200,
  },
  {
    id: "galaxy-s21-ultra-5g",
    marca: "Samsung",
    modelo: "Galaxy S21 Ultra 5G",
    larguraPx: 1824,
    alturaPx: 3200,
  },
  {
    id: "galaxy-s21-5g",
    marca: "Samsung",
    modelo: "Galaxy S21 5G",
    larguraPx: 1839,
    alturaPx: 3200,
  },
  {
    id: "galaxy-s21-plus-5g",
    marca: "Samsung",
    modelo: "Galaxy S21+ 5G",
    larguraPx: 1828,
    alturaPx: 3200,
  },
  {
    id: "galaxy-a42",
    marca: "Samsung",
    modelo: "Galaxy A42",
    larguraPx: 1859,
    alturaPx: 3200,
  },
  {
    id: "galaxy-s10-plus",
    marca: "Samsung",
    modelo: "Galaxy S10+",
    larguraPx: 1871,
    alturaPx: 3200,
  },
  {
    id: "galaxy-note-20",
    marca: "Samsung",
    modelo: "Galaxy Note 20",
    larguraPx: 1863,
    alturaPx: 3200,
  },
  {
    id: "galaxy-note-20-ultra-5g",
    marca: "Samsung",
    modelo: "Galaxy Note 20 Ultra 5G",
    larguraPx: 1853,
    alturaPx: 3200,
  },
  {
    id: "galaxy-s10-lite",
    marca: "Samsung",
    modelo: "Galaxy S10 Lite",
    larguraPx: 1763,
    alturaPx: 3200,
  },
  {
    id: "galaxy-a71-5g",
    marca: "Samsung",
    modelo: "Galaxy A71 5G",
    larguraPx: 1743,
    alturaPx: 3200,
  },
  {
    id: "galaxy-a51-5g",
    marca: "Samsung",
    modelo: "Galaxy A51 5G",
    larguraPx: 1906,
    alturaPx: 3200,
  },
  {
    id: "galaxy-s7",
    marca: "Samsung",
    modelo: "Galaxy S7",
    larguraPx: 1836,
    alturaPx: 3200,
  },
  {
    id: "galaxy-s10e",
    marca: "Samsung",
    modelo: "Galaxy S10e",
    larguraPx: 1961,
    alturaPx: 3200,
  },
  {
    id: "galaxy-s8",
    marca: "Samsung",
    modelo: "Galaxy S8",
    larguraPx: 1790,
    alturaPx: 3200,
  },
  {
    id: "galaxy-note10",
    marca: "Samsung",
    modelo: "Galaxy Note10",
    larguraPx: 1899,
    alturaPx: 3200,
  },
  {
    id: "galaxy-s9",
    marca: "Samsung",
    modelo: "Galaxy S9",
    larguraPx: 1851,
    alturaPx: 3200,
  },
  {
    id: "galaxy-s20",
    marca: "Samsung",
    modelo: "Galaxy S20",
    larguraPx: 1786,
    alturaPx: 3200,
  },
  {
    id: "galaxy-note-8",
    marca: "Samsung",
    modelo: "Galaxy Note 8",
    larguraPx: 1820,
    alturaPx: 3200,
  },
  {
    id: "galaxy-s10",
    marca: "Samsung",
    modelo: "Galaxy S10",
    larguraPx: 1918,
    alturaPx: 3200,
  },
  {
    id: "galaxy-s20-plus",
    marca: "Samsung",
    modelo: "Galaxy S20+",
    larguraPx: 1809,
    alturaPx: 3200,
  },
  {
    id: "galaxy-s9-plus",
    marca: "Samsung",
    modelo: "Galaxy S9+",
    larguraPx: 1863,
    alturaPx: 3200,
  },
  {
    id: "galaxy-note-9",
    marca: "Samsung",
    modelo: "Galaxy Note 9",
    larguraPx: 1873,
    alturaPx: 3200,
  },
  {
    id: "galaxy-note-10-plus",
    marca: "Samsung",
    modelo: "Galaxy Note 10+",
    larguraPx: 1879,
    alturaPx: 3200,
  },
  {
    id: "iphone-17e",
    marca: "Apple",
    modelo: "iPhone 17e",
    larguraPx: 1868,
    alturaPx: 3200,
  },
  {
    id: "iphone-17-pro-max",
    marca: "Apple",
    modelo: "iPhone 17 Pro Max",
    larguraPx: 1800,
    alturaPx: 3200,
  },
  {
    id: "iphone-air",
    marca: "Apple",
    modelo: "iPhone Air",
    larguraPx: 1809,
    alturaPx: 3200,
  },
  {
    id: "iphone-17-pro",
    marca: "Apple",
    modelo: "iPhone 17 Pro",
    larguraPx: 1865,
    alturaPx: 3200,
  },
  {
    id: "iphone-17",
    marca: "Apple",
    modelo: "iPhone 17",
    larguraPx: 1865,
    alturaPx: 3200,
  },
  {
    id: "iphone-16e",
    marca: "Apple",
    modelo: "iPhone 16e",
    larguraPx: 1868,
    alturaPx: 3200,
  },
  {
    id: "iphone-16-plus",
    marca: "Apple",
    modelo: "iPhone 16 Plus",
    larguraPx: 1804,
    alturaPx: 3200,
  },
  {
    id: "iphone-16-pro-max",
    marca: "Apple",
    modelo: "iPhone 16 Pro Max",
    larguraPx: 1804,
    alturaPx: 3200,
  },
  {
    id: "iphone-16",
    marca: "Apple",
    modelo: "iPhone 16",
    larguraPx: 1861,
    alturaPx: 3200,
  },
  {
    id: "iphone-16-pro",
    marca: "Apple",
    modelo: "iPhone 16 Pro",
    larguraPx: 1861,
    alturaPx: 3200,
  },
  {
    id: "iphone-15-pro-max",
    marca: "Apple",
    modelo: "iPhone 15 Pro Max",
    larguraPx: 1748,
    alturaPx: 3200,
  },
  {
    id: "iphone-15-pro",
    marca: "Apple",
    modelo: "iPhone 15 Pro",
    larguraPx: 1778,
    alturaPx: 3200,
  },
  {
    id: "iphone-15-plus",
    marca: "Apple",
    modelo: "iPhone 15 Plus",
    larguraPx: 1748,
    alturaPx: 3200,
  },
  {
    id: "iphone-15",
    marca: "Apple",
    modelo: "iPhone 15",
    larguraPx: 1783,
    alturaPx: 3200,
  },
  {
    id: "iphone-14-plus",
    marca: "Apple",
    modelo: "iPhone 14 Plus",
    larguraPx: 1804,
    alturaPx: 3200,
  },
  {
    id: "iphone-14",
    marca: "Apple",
    modelo: "iPhone 14",
    larguraPx: 1868,
    alturaPx: 3200,
  },
  {
    id: "iphone-14-pro",
    marca: "Apple",
    modelo: "iPhone 14 Pro",
    larguraPx: 1868,
    alturaPx: 3200,
  },
  {
    id: "iphone-14-pro-max",
    marca: "Apple",
    modelo: "iPhone 14 Pro Max",
    larguraPx: 1804,
    alturaPx: 3200,
  },
  {
    id: "iphone-13-mini",
    marca: "Apple",
    modelo: "iPhone 13 mini",
    larguraPx: 1899,
    alturaPx: 3200,
  },
  {
    id: "iphone-13",
    marca: "Apple",
    modelo: "iPhone 13",
    larguraPx: 1868,
    alturaPx: 3200,
  },
  {
    id: "iphone-13-pro-max",
    marca: "Apple",
    modelo: "iPhone 13 Pro Max",
    larguraPx: 1838,
    alturaPx: 3200,
  },
  {
    id: "iphone-13-pro",
    marca: "Apple",
    modelo: "iPhone 13 Pro",
    larguraPx: 1868,
    alturaPx: 3200,
  },
  {
    id: "iphone-12-mini",
    marca: "Apple",
    modelo: "iPhone 12 mini",
    larguraPx: 1916,
    alturaPx: 3200,
  },
  {
    id: "iphone-12",
    marca: "Apple",
    modelo: "iPhone 12",
    larguraPx: 1868,
    alturaPx: 3200,
  },
  {
    id: "iphone-12-pro-max",
    marca: "Apple",
    modelo: "iPhone 12 Pro Max",
    larguraPx: 1853,
    alturaPx: 3200,
  },
  {
    id: "iphone-12-pro",
    marca: "Apple",
    modelo: "iPhone 12 Pro",
    larguraPx: 1868,
    alturaPx: 3200,
  },
  {
    id: "iphone-11",
    marca: "Apple",
    modelo: "iPhone 11",
    larguraPx: 1938,
    alturaPx: 3200,
  },
  {
    id: "iphone-se",
    marca: "Apple",
    modelo: "iPhone SE",
    larguraPx: 1848,
    alturaPx: 3200,
  },
  {
    id: "iphone-xs",
    marca: "Apple",
    modelo: "iPhone XS",
    larguraPx: 1920,
    alturaPx: 3200,
  },
  {
    id: "iphone-7",
    marca: "Apple",
    modelo: "iPhone 7",
    larguraPx: 1848,
    alturaPx: 3200,
  },
  {
    id: "iphone-7-plus",
    marca: "Apple",
    modelo: "iPhone 7 Plus",
    larguraPx: 1864,
    alturaPx: 3200,
  },
  {
    id: "iphone-x",
    marca: "Apple",
    modelo: "iPhone X",
    larguraPx: 1920,
    alturaPx: 3200,
  },
  {
    id: "iphone-8",
    marca: "Apple",
    modelo: "iPhone 8",
    larguraPx: 1848,
    alturaPx: 3200,
  },
  {
    id: "iphone-8-plus",
    marca: "Apple",
    modelo: "iPhone 8 Plus",
    larguraPx: 1864,
    alturaPx: 3200,
  },
  {
    id: "iphone-xs-max",
    marca: "Apple",
    modelo: "iPhone XS Max",
    larguraPx: 2027,
    alturaPx: 3200,
  },
  {
    id: "iphone-11-pro",
    marca: "Apple",
    modelo: "iPhone 11 Pro",
    larguraPx: 1871,
    alturaPx: 3200,
  },
  {
    id: "iphone-xr",
    marca: "Apple",
    modelo: "iPhone XR",
    larguraPx: 1897,
    alturaPx: 3200,
  },
  {
    id: "iphone-11-pro-max",
    marca: "Apple",
    modelo: "iPhone 11 Pro Max",
    larguraPx: 1913,
    alturaPx: 3200,
  },
];

export function getModeloById(id: string): ModeloCelular | undefined {
  return MODELOS.find((m) => m.id === id);
}
